version: "2"

services:

  aut: 
    build: ./docker-aut
    container_name: aut
    image: aut
    depends_on:
      - namenode
      - datamanager1
    ports:
      - "8888:8888"
      - "4040:4040"
      - "4041:4041"
    volumes:
      - D:/Workspaces/ZEW/Mannheim_Web_Panel/03_Documentation/04_WARC_to_SPARK/notebooks:/notebook
      - D:/Workspaces/ZEW/Testing_zone/subset:/data_subset
    env_file:
      - ./hadoop.env

  namenode:
    build: ./namenode
    image: bde2020/hadoop-namenode:1.1.0-hadoop3.2.2-java11
    container_name: namenode
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ports:
      - "9870:9870"
      - "50070:50070"
  
  resourcemanager:
    build: ./resourcemanager
    image: bde2020/hadoop-resourcemanager:1.1.0-hadoop3.2.2-java11
    container_name: resourcemanager
    depends_on:
      - namenode
    env_file:
      - ./hadoop.env
    ports:
      - "8088:8088"
      - "8031:8031"
  
  historyserver:
    build: ./historyserver
    image: bde2020/hadoop-historyserver:1.1.0-hadoop3.2.2-java11
    container_name: historyserver
    depends_on:
      - namenode
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env
    ports:
      - "8188:8188"
  
  # nodemanager1:
  #   build: ./nodemanager
  #   image: bde2020/hadoop-nodemanager:1.1.0-hadoop3.2.2-java11
  #   container_name: nodemanager1
  #   depends_on:
  #     - namenode
  #     - datanode1
  #   env_file:
  #     - ./hadoop.env
  #   ports:
  #     - "8042:8042"
  
  datamanager2:
      build: ./nodedatamanager
      image: bde2020/hadoop-datamanager:1.1.0-hadoop3.2.2-java11
      container_name: datamanager2
      depends_on:
        - namenode
      env_file:
        - ./hadoop.env

  datamanager1:
    build: ./nodedatamanager
    image: bde2020/hadoop-datamanager:1.1.0-hadoop3.2.2-java11
    container_name: datamanager1
    depends_on:
      - namenode
    env_file:
      - ./hadoop.env

  # datanode1:
  #   build: ./datanode
  #   image: bde2020/hadoop-datanode:1.1.0-hadoop3.2.2-java11
  #   container_name: datanode1
  #   depends_on:
  #     - namenode
  #   volumes:
  #     - hadoop_datanode1:/hadoop/dfs/data
  #   env_file:
  #     - ./hadoop.env



volumes:
  aut:
  hadoop_namenode:
  # hadoop_datanode1:
  # hadoop_datanode2:
  # nodemanager1:
  datamanager2:
  datamanager1:
  # nodemanager3:
  hadoop_historyserver: